services:
  - type: web
    name: public-media-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
      - key: MEDIA_PROVIDER
        value: live
      - key: MONTHLY_QUOTA_ENABLED
        value: "true"
      - key: MONTHLY_DOWNLOAD_LIMIT
        value: "5000"
      - key: CORS_ORIGIN
        value: "*"
      - key: RAPIDAPI_KEY
        value: "3e816048ffmshd860f2873aa16f2p127184jsnfb7a9ceab949"
      - key: RAPIDAPI_HOST
        value: "instagram-downloader-v2-scraper-reels-igtv-posts-stories.p.rapidapi.com"
